webapp/__init__.py
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.uuid import FlaskUUID

from flask.ext.user import UserManager, UserMixin, SQLAlchemyAdapter
from flask.ext.user import current_user, login_required, roles_required, UserMixin

from flask import g

from .api import api
from .data import data
from .modeller import modeller
from .site import site
from .admin import admin
from .status import status
from .install import install

app = Flask(__name__)

#g.test = "lala"

FlaskUUID(app)

#Load the base configuration from settings.py
app.config.from_object('webapp.settings')

#Overwrite any settings with local_settings.py
try: app.config.from_object('webapp.local_settings')
except: print " * Local settings file coult not be imported."

from models import *

db.init_app(app)

@app.context_processor
def system_status():
    """
    This context processor makes the "system_status" variable available in all
    the templates.
    """
    status = {
        'beanstalk_workers': beanstalk.workers
    }
    return dict(system_status=status)

db_adapter = SQLAlchemyAdapter(db,  User)
user_manager = UserManager(db_adapter, app)

app.register_blueprint(modeller,    url_prefix='/modeller')
app.register_blueprint(data,        url_prefix='/data')
app.register_blueprint(api,         url_prefix='/api/v1')
app.register_blueprint(admin,       url_prefix='/admin')
app.register_blueprint(status,      url_prefix='/status')
app.register_blueprint(install,     url_prefix='/install')
app.register_blueprint(site)

if __name__ == "__main__":
	app.run()

webapp/admin/__init__.py
from flask import Blueprint

admin=Blueprint('admin',__name__,template_folder='templates',static_folder='static')

#@admin.before_request
#def restrict_to_admin_roles():
#    if not user.is_admin:
#        return redirect(...)

import views

webapp/admin/views.py
import os
import re
import subprocess
import uuid
import json
import glob 
import StringIO
import tempfile

from osgeo import ogr,osr
from owslib.wcs import WebCoverageService

from . import admin

from flask import g, current_app, render_template, request, jsonify, make_response, flash, url_for, redirect
from flask.ext.user import login_required, roles_required
from datetime import datetime, timedelta

from ..models import *

@admin.route('/')
@roles_required('admin')
def home():
    return 'Hello, admin blueprint!'

@admin.route('/datasets')
@roles_required('admin')
def datasets():
    """
    Shows information on datasets
    """
    wcss=[]
    for descr,url in current_app.config.get('WCS',{}).items():
        layers=[]
        wcs = WebCoverageService(url, version='1.0.0')
        for lyr in list(wcs.contents):
            layers.append({'name':lyr,'data':wcs.contents[lyr]})
            print dir(wcs.contents[lyr])
        wcss.append({'url':url,'layers':layers})
    return render_template("admin/datasets.html",wcs=wcss)
    
@admin.route('/users', methods=["GET"])
@roles_required('admin')
def users():
    """
    Show user list with options to add admins.
    """
    users=User.query.order_by(User.id).all()
    return render_template("admin/users.html",users=users)

@admin.route('/users/<int:uid>/<string:role>/toggle', methods=["GET"])
@roles_required('admin')
def users_make_admin(uid,role):
    """
    Show user list with options to add admins.
    """
    user = User.query.get(uid)
    if user.username != 'admin':
        user.toggle_role(role)
    return redirect(url_for('admin.users'))
    
@admin.route('/users/<int:uid>/reset-api-token')
@roles_required('admin')
def users_reset_api_token(uid):
    user = User.query.get(uid)
    user.reset_api_token()
    return redirect(url_for('admin.users'))

@admin.route('/users/<int:uid>/reset-password')
@roles_required('admin')
def users_reset_password(uid):
    user = User.query.get(uid)
    new_password = user.reset_password()
    flash("New password for user <code>%s</code> is <code>%s</code>. Please write it down, this is the only time that it is shown."%(user.username,new_password),"ok")
    return redirect(url_for('admin.users'))

@admin.route('/discretization',methods=["GET","POST"])
@roles_required('admin')
def discretization():
    """
    Shows information on domain discretization
    """
    if request.method=="POST":
        #try:
        if True:
            f = request.files['shapefile']
            temp = tempfile.NamedTemporaryFile(prefix='de-', suffix='.zip')
            f.save(temp.name)
            ds = ogr.Open("/vsizip/"+temp.name)
            if ds is not None:
                d = Discretization(request.form.get('name',''), ds, int(request.form.get('cellsize',100)))
                db.session.add(d) 
                db.session.commit()
                flash("New discretization was created!","ok")
            else:
                raise Exception("Temporary file '%s' could not be opened."%(temp.name))
        #except Exception as e:
        #    db.session.rollback()
        #    flash("An exception occurred while trying to add the discretization! Hint: %s"%(e),"error")
        #finally:
            ds = None
            temp.close()
        return redirect(url_for('admin.discretization'))
    else:
        return render_template("admin/discretization.html",discretizations=Discretization.query.all())

@admin.route('/processing')
@roles_required('admin')
def processing():
    """
    Shows information on processing
    """
    jobs=Job.query.order_by(Job.date_created.desc()).limit(10)
    return render_template("admin/processing.html",jobs=jobs)
    

@admin.route('/notifications')
@roles_required('admin')
def notifications():
    """
    Show notifications sent via postgresql NOTIFY
    """
    return render_template("admin/notifications.html")

@admin.route('/workers')
@roles_required('admin')
def workers():
    """
    Shows information on connected workers
    """
    workers = Worker.query.order_by(Worker.updated.desc()).limit(10)
    return render_template("admin/workers.html", workers=workers)

@admin.route('/models/<model_name>/editor',methods=["GET","POST"])
def model_editor(model_name):
    """
    show the code editor
    """
    model=Model.query.filter_by(name=model_name).first_or_404()
    return render_template('admin/modeleditor.html',model=model)
    
@admin.route('/models/<model_name>/toggle-pin',methods=["GET"])
@roles_required('admin')
def model_toggle_pin(model_name):
    model = Model.query.filter_by(name=model_name).first_or_404()
    model.toggle_pin()
    return redirect(url_for('site.home'))
    
@admin.route('/models/<model_name>/toggle-disable',methods=["GET"])
@roles_required('admin')
def model_toggle_disable(model_name):
    model = Model.query.filter_by(name=model_name).first_or_404()
    model.toggle_disable()
    return redirect(url_for('site.home'))

@admin.route('/models/<model_name>/parameters',methods=["GET","POST"])
def model_parameters(model_name):
    """
    show the code editor
    """
    model=Model.query.filter_by(name=model_name).first_or_404()
    return render_template('admin/modelparameters.html',model=model)    

@admin.route('/models',methods=["GET","POST"])
@roles_required('admin')
def models():
    """
    Shows information on models
    """
    if request.method=="POST":
#        name=re.sub(r'\W+',' ',request.form.get("modelname","")).lower()
#        name="_".join(map(str,name.split()))
#        
#        if name == "":
#            flash("Invalid model name.")
#            return redirect(url_for('site.home'))
#        
#        model = Model.query.filter_by(name=name).first()
#        if model is not None:
#            flash("It seems like that model exists already! Please try another name.","error")
#            return redirect(url_for('site.home'))
        
        try:
            model = Model(name=request.form.get("modelname",""))
            db.session.add(model)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            flash("Something unexpected went wrong trying to add the model. Hint: %s"%(e),"error")
            return redirect(url_for('site.home'))
        else:
            return redirect(url_for('admin.model_editor',model_name=model.name))
    else:
        flash("The models admin page is no longer in use because all the models are now listed on the homepage.","info")
        return redirect(url_for('site.home'))
        

webapp/api/__init__.py
from flask import Blueprint

api=Blueprint('api',__name__)

import views

webapp/data/__init__.py
from flask import Blueprint

data=Blueprint('data',__name__)

import views

webapp/install/__init__.py
from flask import Blueprint

install = Blueprint('install', __name__, template_folder='templates', static_folder='static')

import views

webapp/modeller/__init__.py
from flask import Blueprint

modeller=Blueprint('modeller',__name__,template_folder='templates',static_folder='static')

import views

webapp/modeller/views.py
import os
import re
import subprocess
import uuid
import json

from . import modeller

from flask import g, current_app, render_template, request, jsonify, make_response, render_template, abort, redirect, url_for
from datetime import datetime, timedelta

from ..models import *

@modeller.route('/<model_name>')
def show_modeller(model_name):
    m = Model.query.filter(Model.name==model_name).first_or_404()
    if not m.validated:
        flash("Model '%s' has not been validated and cannot be run in the modeller."%(m.name),"error")
        return redirect(url_for('site.home'))
    if m.disabled:
        flash("Model has been deleted.")
        return redirect(url_for('site.home'))
        
    return render_template('modeller/modeller.html', model=m, discretization=m.discretization, u=current_user)

webapp/site/__init__.py
from flask import Blueprint

site = Blueprint('site', __name__, template_folder='templates', static_folder='static')

import views

webapp/site/views.py
import os
import re
import subprocess
import uuid
import json

from . import site

from flask import g, current_app, render_template, request, jsonify, make_response, redirect, url_for
from flask.ext.user import login_required, roles_required
from datetime import datetime, timedelta

from ..models import *


@site.route('/')
def home():
    if current_user.is_anonymous():
        return redirect(url_for('user.login'))
    else:
        #The highlighted models which are available to all users
        models = Model.query.order_by(Model.name).filter(Model.highlighted==True, Model.disabled==False).all()
        
        #The other (test) models which are not on the homepage.
        other_models = Model.query.order_by(Model.disabled, Model.name).filter(Model.highlighted==False).all()
        return render_template("site/home.html", models=models, other_models=other_models)
        
@site.route('/myaccount')
@login_required
def myaccount():
    return render_template("site/myaccount.html")
    
@site.route('/myaccount/reset-api-token')
@login_required
def myaccount_reset_api_token():
    current_user.reset_api_token()
    return redirect(url_for('site.home'))
    

@site.route('/models')
def models():
    return render_template("site/models.html", models=Model.query.all())
 
@site.route('/features')
def features():
    return render_template("site/features.html")
 
@site.route('/about')
def about():
    return render_template("site/about.html")
 
@site.route('/datasources')
def datasources():
    return render_template("site/datasources.html")

webapp/status/__init__.py
from flask import Blueprint

status = Blueprint('status', __name__, template_folder='templates', static_folder='static')

import views

webapp/status/views.py
import os
import re
import subprocess
import uuid
import json

from . import status

from flask import g, current_app, render_template, request, jsonify, make_response, flash
from datetime import datetime, timedelta

from ..models import *

@status.route('')
def home():
    """
    
    Todo:
    
    - status of beanstalk queue rather than entire server
    - mappsever status
    - databsae status
    - mapserver connect
    
    """
    return render_template("status/status.html", beanstalk=beanstalk)

webapp/templates/modeller/header.html
<nav class="navbar navbar-default navbar-inverse " role="navigation">
  <div class="container-fluid">
      <ul class="nav navbar-nav navbar-left">


        <!--<li class="active"><a href="/"><i class="fa fa-flag"></i> <strong>Fieldwork France 2014</strong> <i class="fa fa-angle-right"></i> Group A</a></li>-->
        <!--<li class="active"><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>-->
        <li><a href="/"><i class="fa fa-flag"></i> Home</a></li>
        <li><a href="/admin/datasets"><i class="fa fa-database"></i> Datasets</a></li>
        <li><a href="/admin/discretization"><i class="fa fa-pie-chart"></i> Domain Discretization</a></li>
        <li><a href="/admin/processing"><i class="fa fa-gear"></i> Processing</a></li>
        <li><a href="/admin/models"><i class="fa fa-leaf"></i> Models</a></li>
        <li><a href="/admin/configuration"><i class="fa fa-wrench"></i> Configuration</a></li>
        <li><a href="/admin/status"><i class="fa fa-line-chart"></i> Status</a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="/"><i class="fa fa-flag"></i> Home</a></li>
        <li><a href="/admin/datasets"><i class="fa fa-database"></i> Datasets</a></li>
      </ul>

      	<p class="navbar-text pull-right" style="color:#aaa;">
      		<i class="fa fa-cog"></i> 
      		Running model pcrtopo
      	</p> 


    <!--</div>--><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

webapp/templates/modeller/modeller.html
{% extends "base.html" %}

{% block footjs %}
	<script src="/static/lib/jquery/jquery-debounce.js"></script>
	

	<script src="/static/lib/leaflet/leaflet.js"></script>
	<script src="/static/lib/leaflet-plugins/grid/L.Grid.js"></script>


	<!-- script src="/static/lib/chart/Chart.min.js"></script -->

	<script src="/static/lib/flot/jquery.flot.min.js"></script>
	<script src="/static/lib/flot/jquery.flot.time.min.js"></script>
	<script src="/static/lib/flot/jquery.flot.selection.min.js"></script>

	<script src="/static/lib/gem/modeller.js"></script>
	<script src="/static/lib/gem/modeller-gui.js"></script>
	<script src="/static/lib/gem/modeller-api.js"></script>
	<script src="/static/lib/gem/modeller-legends.js"></script>
	<script src="/static/lib/gem/modeller-charts.js"></script>
	<script src="/static/lib/gem/geohash.js"></script>
	<script src="/static/lib/gem/util.js"></script>

	<script type="text/javascript">
		// $('form#jobform').on("submit",function(evt){
		// 	evt.preventDefault();
		// 	$(this).find("input[name='bbox']").val(map.getBounds().toBBoxString())
		// 	$.ajax({
		// 		type: "POST",
		// 		url:$(this).attr('action'),
		// 		data:$(this).serialize(),
		// 		success: function(data) {
		// 			console.log("SUCCESS!")
		// 		},
		// 		error: function(){
		// 			console.log("FAILURE!!")
		// 		}
		// 	})
		// })

		$('#menu-editcode').tooltip({
			html:true,
			placement:'auto',
			title:'Activate the inline editing console.<br/><span style="color:#666;"><nobr> Ctrl&ndash;M</nobr></span>',
			trigger:'hover focus',
			viewport:{ selector: 'body', padding: 7 }
		})

		$('#menu-moreoptions').tooltip({
			html:true,
			placement:'auto',
			title:'More options.',
			trigger:'hover focus',
			viewport:{ selector: 'body', padding: 7 }
		})

		$('#menu-editparameters').tooltip({
			html:true,
			placement:'auto',
			title:'Edit the input or calibration parameters for this model.<br/><span style="color:#666;"><nobr> Ctrl&ndash;E</nobr></span>',
			trigger:'hover focus',
			viewport:{ selector: 'body', padding: 7 }
		})

		$(document).ready(function() { 
			M.init({
				model:'{{model.name}}',
				mapfile:'{{model.mapserver_mapfile}}',
				mapserver:'{{url_for("data.mapserver")}}',
				api:'{{url_for("api.home")}}',
				api_auth_username:'{{current_user.username}}',
				api_auth_token:'{{current_user.api_token}}',
				default_config_key:'{{model.default_config_key}}',
				default_view_extent:'{{discretization.extent_as_bounds}}',
				hash:'{{model.default_modeller_hash}}',
				geonames_api_username:'{{config["GEONAMES_API_USERNAME"]}}'
			}); 
		});

	</script>
{% endblock %}

{% block header %}

<nav class="navbar navbar-default navbar-inverse " role="navigation">
  <div id="waiting">&nbsp;</div>
  <div class="container-fluid">
      <ul class="nav navbar-nav navbar-left">
      <!--<li><a href="{{ url_for('site.home')}}" style="padding:0;padding-left:15px;padding-top:10px;padding-bottom:10px;padding-right:15px;"><img src="/static/gfx/gems-logo-cube.png" style="border:0;height:30px;"></a></li>-->
        <li><a href="{{ url_for('site.home')}}" id="menu-switch"><i class="fa fa-arrow-left"></i> Home</a></li>
        <li><a href="#" id="menu-run"><i class="fa fa-play"></i> Run</a></li>
        <li><a href="#" id="menu-editparameters"><i class="fa fa-wrench"></i> <u>E</u>dit parameters</a></li>
        <!--<li><a href="#" id="menu-editcode"><i class="fa fa-pencil"></i> Edit code</a></li>-->
        <li><a href="#" id="menu-findplaces"><i class="fa fa-search"></i> <u>F</u>ind places</a></li>
        <!--<li><a href="/admin/datasets"><i class="fa fa-star"></i> Favorites</a></li>-->
      </ul>
    {% if not current_user.is_anonymous() %}
      <a href="{{url_for('user.logout')}}" class="btn btn-default navbar-btn pull-right" style="background-color:#111;border-color:#555;color:#aaa;margin-left:15px;"><i class="fa fa-close"></i> Log Out</a>
      <a href="{{url_for('site.myaccount')}}" class="btn btn-default navbar-btn pull-right" style="background-color:#111;border-color:#555;color:#aaa;margin-left:15px;"><i class="fa fa-user"></i> My Account</a>
    {% endif %}
		<ul class="nav navbar-nav navbar-right">
			<li><a href="{{url_for('site.datasources')}}" style="color:#888;"><i class="fa fa-caret-right"></i> Data sources and attribution</a></li>
			<li><a href="{{url_for('site.about')}}" style="color:#888;"><i class="fa fa-caret-right"></i> About this project</a></li>
			<li><a href="{{url_for('status.home')}}" style="color:#888;" target="_blank"><i class="fa fa-caret-right"></i> System status</a></li>
		</ul>



    <!--</div>--><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


{% endblock %}

{% block headjs %}

{% endblock %}

{% block headcss %}
	<link rel="stylesheet" href="/static/lib/leaflet/leaflet.css" />
	<link rel="stylesheet" href="/static/lib/leaflet-plugins/grid/L.Grid.css" />
	<link rel="stylesheet" href="/static/lib/gem/modeller.css" />
	<style>
	.leaflet-grid-label .lng {
margin-left: 8px;
-webkit-transform: rotate(90deg);
transform: rotate(90deg);
}
.leaflet-grid-label .lat,
.leaflet-grid-label .lng {
text-shadow: none;
opacity:0.8;
}

</style>
{% endblock %}

{% block modeller %}
	
	{% if modelconfiguration %}
		loading with configuration
	{% endif %}

		<div id="map"></div>

		<div id="panel" class="map-control map-control-left" style="margin:0px;padding:0px;">
			<div id="panel-notifications" class="map-panel">
				<h2> Please wait while your model is run</h2>

				<div class="progress" style="margin-top:10px;height:7px;border-radius:2px;margin-bottom:7px;">
				  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
				    <span class="sr-only"></span>
				  </div>
				</div>

				<p style="margin-bottom:0px;" id="notification-message"></p>
				<div id="notification" style="display:none;"></div>
			</div>
			<div id="panel-params" class="map-panel">
				<h2>Model parameters</h2>
				<form id="model-parameters" action="/api/v1/job" method="POST" class="form-horizontal">
					<div class="form-group" style="display:none;">
						<label for="model_name" class="col-sm-7 control-label">Model Identifier</label>
						<div class="col-sm-5">
							<input type="text" class="form-control input-sm" name="model_name" style="width:100%;text-align:center;" value="{{model.name}}">
						</div>
					</div>
					{% for parameter in model.parameters %}
					<div class="form-group">
						<label for="{{parameter}}" class="col-sm-7 control-label">{{parameter}}</label>
						<div class="col-sm-5">
							<input type="text" class="form-control input-sm" id="{{parameter}}" placeholder="" name="{{parameter}}" style="width:100%;text-align:center;" value="###">
							<!-- 
							The '###' values will be replaced when a JavaScript loads the 
							actual parameters corresponding to the model configuration.
							-->
						</div>
					</div>
					{% endfor %}
				</form>
				<!--<a href="#" id="close-params-link"><i class="fa fa-chevron-left"></i></a>-->
			</div>
			<div id="panel-findplaces" class="map-panel">
            	<h2>Find places</h2>
                <p>
                Enter a location such as a city or country nearby where you would like to run your model.
                </p>
                <form id="find-places" action="http://api.geonames.org/searchJSON" method="GET">
                	<input type="hidden" name="username" value="kokoalberti" />
                	<input type="hidden" name="maxRows" value="6" />

					<div class="form-group" style="margin-bottom:10px;">
						<input type="text" class="form-control input-sm" placeholder="Eg: Monaco, Mont Blanc, Bonaire, Cagliari, Malta, etc." name="q" style="width:100%;text-align:left;">
					</div>
					<div id="results-list" style="margin:0" class="list-group"></div>
		        </form>
	        </div>
		</div>

		<div id="panel-attributes" class="map-control map-control-right" style="width:350px;">
			<h2>Output layers</h2>
			<p style="color:#888;">Hint: Hold down SPACE to quickly show and hide the data layer.</p>
			<form class="form-horizontal" id="attribute-form">
				{% for attribute in model.reporting %}
				<div class="radio">
					<label><input type="radio" name="selected-attribute" id="selected-attribute-{{attribute}}" value="{{attribute}}">{{model.reporting[attribute]['title']}} <!--[{{model.reporting[attribute]['units']}}]--></label>
				</div>
				{% endfor %}

			</form>		
			<div id="panel-timesteps">
				<hr/>
				<strong>Timesteps</strong><br/>
				<p id="panel-timesteps-label" style="margin-top:0px;margin-bottom:4px;font-weight:bold;"></p>
				<select id="selected-timestamp" size="3" style="width:100%;">
					<!--
					{% for timestamp in model.timestamp_list %}
					<option value="{{timestamp}}">{{loop.index}}. {{timestamp}}</option>
					{% endfor %}
					-->
				</select>
			</div>

			<hr/>
			<div id="panel-legend">
				{% for attribute in model.reporting %}
				<div id="legend-item-{{attribute}}" class="legend-item" data-legend-for-attribute="{{attribute}}">
					<h2>
					{{ model.reporting[attribute].title }} [{{model.reporting[attribute].units}}]
					</h2>

					{% if model.reporting[attribute].symbolizer.type == "categorical" or model.reporting[attribute].symbolizer.type == "classified" %}
						<ul class="legend-items">
						{% for label in model.reporting[attribute].symbolizer.labels %}
							<li>
								<div class="legend-item-colorsample" style="background-color:{{model.reporting[attribute].symbolizer.colors[loop.index0]}}"></div>
								{{label}}
							</li>
						{% endfor %}
						</ul>
					{% endif %}
					{% if model.reporting[attribute].symbolizer.type == "pseudocolor" %}
						<div style="display:block;position:relative;width:100%;height:30px;">
							<ul class="ticks" id="ticks-for-{{attribute}}">
								<li style="left:0%">0</li>
								<li style="left:20%">100</li>
								<li style="left:40%">200</li>
								<li style="left:50%">300</li>
								<li style="left:80%">400</li>
								<li style="left:100%">500</li>
							</ul>
						</div>
						<canvas 
							id="legend-item-{{attribute}}-colormap" 
							width="255" 
							height="28" 
							class="legend-colormap" 
							data-layer="{{attribute}}" 
							data-color-stops="{% for color in model.reporting[attribute].symbolizer.colors %}{{color}} {% endfor %}" 
							data-min="{{ model.reporting[attribute].symbolizer['values'][0] }}" 
							data-max="{{ model.reporting[attribute].symbolizer['values'][1] }}" 
							data-ticks="{{model.reporting[attribute].symbolizer['ticks']}}" 
							data-ticks-ul="ticks-for-{{attribute}}">
						</canvas>
					{% endif %}
					<p>{{ model.reporting[attribute].info }}</p>
				</div>
				{% endfor %}
				

				<div id="legend-chart-timeseries" class="legend-chart" data-chart-id="timeseries">
					<hr/>
					<h2>Timeseries</h2>
					<p style="color:#888;">Hint: Click a location on the map to view the timeseries data.</p>
					<div id="legend-chart-timeseries-placeholder" class="legend-chart-placeholder">
					</div>
					<!--
					<canvas id="legend-chart-timeseries-canvas" width="255" height="160" style="width:255px;height:160px;border:1px solid black;"></canvas>
					-->
				</div>

				<!--
				{% for attribute in model.reporting %}
				{% if model.reporting[attribute].symbolizer.type == "pseudocolor" %}

				<div id="legend-chart-{{attribute}}" class="legend-chart">
					<hr/>
					<h2>Timeseries: {{ model.reporting[attribute].title }}</h2>
					<p style="color:#888;">Hint: Click a location on the map to view the timeseries data.</p>
					<canvas 
						id="legend-chart-canvas-{{attribute}}"
						data-min="{{ model.reporting[attribute].symbolizer['values'][0] }}" 
						data-max="{{ model.reporting[attribute].symbolizer['values'][1] }}" 
						data-ticks="{{model.reporting[attribute].symbolizer['ticks']}}"
						data-labels="1,2,3,4,5,6,7,8,9,10,11,12" 
						data-timesteps="{{model.time['timesteps']}}" 
						data-for-attribute="{{attribute}}" 
						width="255" 
						height="160">
					</canvas>
				</div>
				{% endif %}
				{% endfor %}
				-->

			</div>
			<!--
			<hr/>
			<p>
			Developed by the <a target="_blank" href="http://pcraster.geo.uu.nl">PCRaster</a> team at Utrecht University. Find out about <a target="_blank" href="http://virtualglobe.geo.uu.nl/datasets/">data sources and attribution</a> or <a href="#">developing your own models</a>.
			</p>
			-->
		</div>
<div id="log-modal" class="modal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    <!--
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Log file</h4>
      </div>-->
      <div class="modal-body" id="log-modal-content" style="white-space:pre;display:block;unicode-bidi:embed;font-family:'Courier New',monospace;font-size:8pt;height:400px;overflow-y:scroll;overflow-x:hidden"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}