webapp/__init__.py
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.uuid import FlaskUUID

from flask.ext.user import UserManager, UserMixin, SQLAlchemyAdapter
from flask.ext.user import current_user, login_required, roles_required, UserMixin

from flask import g

from .api import api
from .data import data
from .modeller import modeller
from .site import site
from .admin import admin
from .status import status
from .install import install

app = Flask(__name__)

#g.test = "lala"

FlaskUUID(app)

#Load the base configuration from settings.py
app.config.from_object('webapp.settings')

#Overwrite any settings with local_settings.py
try: app.config.from_object('webapp.local_settings')
except: print " * Local settings file coult not be imported."

from models import *

db.init_app(app)

@app.context_processor
def system_status():
    """
    This context processor makes the "system_status" variable available in all
    the templates.
    """
    status = {
        'beanstalk_workers': beanstalk.workers
    }
    return dict(system_status=status)

db_adapter = SQLAlchemyAdapter(db,  User)
user_manager = UserManager(db_adapter, app)

app.register_blueprint(modeller,    url_prefix='/modeller')
app.register_blueprint(data,        url_prefix='/data')
app.register_blueprint(api,         url_prefix='/api/v1')
app.register_blueprint(admin,       url_prefix='/admin')
app.register_blueprint(status,      url_prefix='/status')
app.register_blueprint(install,     url_prefix='/install')
app.register_blueprint(site)

if __name__ == "__main__":
	app.run()

webapp/admin/__init__.py
from flask import Blueprint

admin=Blueprint('admin',__name__,template_folder='templates',static_folder='static')

#@admin.before_request
#def restrict_to_admin_roles():
#    if not user.is_admin:
#        return redirect(...)

import views

webapp/admin/views.py
import os
import re
import subprocess
import uuid
import json
import glob 
import StringIO
import tempfile

from osgeo import ogr,osr
from owslib.wcs import WebCoverageService

from . import admin

from flask import g, current_app, render_template, request, jsonify, make_response, flash, url_for, redirect
from flask.ext.user import login_required, roles_required
from datetime import datetime, timedelta

from ..models import *

@admin.route('/')
@roles_required('admin')
def home():
    return 'Hello, admin blueprint!'

@admin.route('/datasets')
@roles_required('admin')
def datasets():
    """
    Shows information on datasets
    """
    wcss=[]
    for descr,url in current_app.config.get('WCS',{}).items():
        layers=[]
        wcs = WebCoverageService(url, version='1.0.0')
        for lyr in list(wcs.contents):
            layers.append({'name':lyr,'data':wcs.contents[lyr]})
            print dir(wcs.contents[lyr])
        wcss.append({'url':url,'layers':layers})
    return render_template("admin/datasets.html",wcs=wcss)
    
@admin.route('/users', methods=["GET"])
@roles_required('admin')
def users():
    """
    Show user list with options to add admins.
    """
    users=User.query.order_by(User.id).all()
    return render_template("admin/users.html",users=users)

@admin.route('/users/<int:uid>/<string:role>/toggle', methods=["GET"])
@roles_required('admin')
def users_make_admin(uid,role):
    """
    Show user list with options to add admins.
    """
    user = User.query.get(uid)
    if user.username != 'admin':
        user.toggle_role(role)
    return redirect(url_for('admin.users'))
    
@admin.route('/users/<int:uid>/reset-api-token')
@roles_required('admin')
def users_reset_api_token(uid):
    user = User.query.get(uid)
    user.reset_api_token()
    return redirect(url_for('admin.users'))

@admin.route('/users/<int:uid>/reset-password')
@roles_required('admin')
def users_reset_password(uid):
    user = User.query.get(uid)
    new_password = user.reset_password()
    flash("New password for user <code>%s</code> is <code>%s</code>. Please write it down, this is the only time that it is shown."%(user.username,new_password),"ok")
    return redirect(url_for('admin.users'))

@admin.route('/discretization',methods=["GET","POST"])
@roles_required('admin')
def discretization():
    """
    Shows information on domain discretization
    """
    if request.method=="POST":
        #try:
        if True:
            f = request.files['shapefile']
            temp = tempfile.NamedTemporaryFile(prefix='de-', suffix='.zip')
            f.save(temp.name)
            ds = ogr.Open("/vsizip/"+temp.name)
            if ds is not None:
                d = Discretization(request.form.get('name',''), ds, int(request.form.get('cellsize',100)))
                db.session.add(d) 
                db.session.commit()
                flash("New discretization was created!","ok")
            else:
                raise Exception("Temporary file '%s' could not be opened."%(temp.name))
        #except Exception as e:
        #    db.session.rollback()
        #    flash("An exception occurred while trying to add the discretization! Hint: %s"%(e),"error")
        #finally:
            ds = None
            temp.close()
        return redirect(url_for('admin.discretization'))
    else:
        return render_template("admin/discretization.html",discretizations=Discretization.query.all())

@admin.route('/processing')
@roles_required('admin')
def processing():
    """
    Shows information on processing
    """
    jobs=Job.query.order_by(Job.date_created.desc()).limit(10)
    return render_template("admin/processing.html",jobs=jobs)
    

@admin.route('/notifications')
@roles_required('admin')
def notifications():
    """
    Show notifications sent via postgresql NOTIFY
    """
    return render_template("admin/notifications.html")

@admin.route('/workers')
@roles_required('admin')
def workers():
    """
    Shows information on connected workers
    """
    workers = Worker.query.order_by(Worker.updated.desc()).limit(10)
    return render_template("admin/workers.html", workers=workers)

@admin.route('/models/<model_name>/editor',methods=["GET","POST"])
def model_editor(model_name):
    """
    show the code editor
    """
    model=Model.query.filter_by(name=model_name).first_or_404()
    return render_template('admin/modeleditor.html',model=model)
    
@admin.route('/models/<model_name>/toggle-pin',methods=["GET"])
@roles_required('admin')
def model_toggle_pin(model_name):
    model = Model.query.filter_by(name=model_name).first_or_404()
    model.toggle_pin()
    return redirect(url_for('site.home'))
    
@admin.route('/models/<model_name>/toggle-disable',methods=["GET"])
@roles_required('admin')
def model_toggle_disable(model_name):
    model = Model.query.filter_by(name=model_name).first_or_404()
    model.toggle_disable()
    return redirect(url_for('site.home'))

@admin.route('/models/<model_name>/parameters',methods=["GET","POST"])
def model_parameters(model_name):
    """
    show the code editor
    """
    model=Model.query.filter_by(name=model_name).first_or_404()
    return render_template('admin/modelparameters.html',model=model)    

@admin.route('/models',methods=["GET","POST"])
@roles_required('admin')
def models():
    """
    Shows information on models
    """
    if request.method=="POST":
#        name=re.sub(r'\W+',' ',request.form.get("modelname","")).lower()
#        name="_".join(map(str,name.split()))
#        
#        if name == "":
#            flash("Invalid model name.")
#            return redirect(url_for('site.home'))
#        
#        model = Model.query.filter_by(name=name).first()
#        if model is not None:
#            flash("It seems like that model exists already! Please try another name.","error")
#            return redirect(url_for('site.home'))
        
        try:
            model = Model(name=request.form.get("modelname",""))
            db.session.add(model)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            flash("Something unexpected went wrong trying to add the model. Hint: %s"%(e),"error")
            return redirect(url_for('site.home'))
        else:
            return redirect(url_for('admin.model_editor',model_name=model.name))
    else:
        flash("The models admin page is no longer in use because all the models are now listed on the homepage.","info")
        return redirect(url_for('site.home'))
        

webapp/api/__init__.py
from flask import Blueprint

api=Blueprint('api',__name__)

import views

webapp/data/__init__.py
from flask import Blueprint

data=Blueprint('data',__name__)

import views

webapp/install/__init__.py
from flask import Blueprint

install = Blueprint('install', __name__, template_folder='templates', static_folder='static')

import views

webapp/modeller/__init__.py
from flask import Blueprint

modeller=Blueprint('modeller',__name__,template_folder='templates',static_folder='static')

import views

webapp/modeller/views.py
import os
import re
import subprocess
import uuid
import json

from . import modeller

from flask import g, current_app, render_template, request, jsonify, make_response, render_template, abort, redirect, url_for
from datetime import datetime, timedelta

from ..models import *

@modeller.route('/<model_name>')
def show_modeller(model_name):
    m = Model.query.filter(Model.name==model_name).first_or_404()
    if not m.validated:
        flash("Model '%s' has not been validated and cannot be run in the modeller."%(m.name),"error")
        return redirect(url_for('site.home'))
    if m.disabled:
        flash("Model has been deleted.")
        return redirect(url_for('site.home'))
        
    return render_template('modeller/modeller.html', model=m, discretization=m.discretization, u=current_user)

webapp/site/__init__.py
from flask import Blueprint

site = Blueprint('site', __name__, template_folder='templates', static_folder='static')

import views

webapp/site/views.py
import os
import re
import subprocess
import uuid
import json

from . import site

from flask import g, current_app, render_template, request, jsonify, make_response, redirect, url_for
from flask.ext.user import login_required, roles_required
from datetime import datetime, timedelta

from ..models import *


@site.route('/')
def home():
    if current_user.is_anonymous():
        return redirect(url_for('user.login'))
    else:
        #The highlighted models which are available to all users
        models = Model.query.order_by(Model.name).filter(Model.highlighted==True, Model.disabled==False).all()
        
        #The other (test) models which are not on the homepage.
        other_models = Model.query.order_by(Model.disabled, Model.name).filter(Model.highlighted==False).all()
        return render_template("site/home.html", models=models, other_models=other_models)
        
@site.route('/myaccount')
@login_required
def myaccount():
    return render_template("site/myaccount.html")
    
@site.route('/myaccount/reset-api-token')
@login_required
def myaccount_reset_api_token():
    current_user.reset_api_token()
    return redirect(url_for('site.home'))
    

@site.route('/models')
def models():
    return render_template("site/models.html", models=Model.query.all())
 
@site.route('/features')
def features():
    return render_template("site/features.html")
 
@site.route('/about')
def about():
    return render_template("site/about.html")
 
@site.route('/datasources')
def datasources():
    return render_template("site/datasources.html")

webapp/status/__init__.py
from flask import Blueprint

status = Blueprint('status', __name__, template_folder='templates', static_folder='static')

import views

webapp/status/views.py
import os
import re
import subprocess
import uuid
import json

from . import status

from flask import g, current_app, render_template, request, jsonify, make_response, flash
from datetime import datetime, timedelta

from ..models import *

@status.route('')
def home():
    """
    
    Todo:
    
    - status of beanstalk queue rather than entire server
    - mappsever status
    - databsae status
    - mapserver connect
    
    """
    return render_template("status/status.html", beanstalk=beanstalk)

webapp/templates/site/about.html
{% extends "base.html" %}

{% block content %}

	<h2>About this project</h2>

	<p>
	Some information about this project.
	</p>

{% endblock %}

webapp/templates/site/datasources.html
{% extends "base.html" %}

{% block content %}

	<h2>Datasources</h2>

	<p>
	Overview of the available datasources
	</p>

{% endblock %}

webapp/templates/site/features.html
{% extends "base.html" %}

{% block content %}

	<h2>Features</h2>

	<p>
	List of the available features
	</p>

{% endblock %}

webapp/templates/site/home.html
{% extends "base.html" %}


{% block headcss %}

	<style>
		a:hover {
			text-decoration:none;
		}
	</style>
{% endblock %}

{% block content %}

	<div class="row" style="margin-top:15px;">
		{% if not models %}
			<div class="col-md-8 col-sm-8">
				<div class="panel panel-default" style="padding-bottom:0">
					<div class="panel-heading">
						<strong>Models</strong>
					</div>
					<div class="panel-body">
						<p>No environmental models found in the system. Some models should have been created when installing.</p>
					</div>
				</div>
			</div>
		{% else %}
			<div class="col-md-8 col-sm-8">
				<div class="row">
				{% for columns in models | slice(2) -%}
					<div class="col-md-6 col-sm-6">
					{%- for model in columns -%}
						<div class="panel panel-default">
						  <div class="panel-heading" style="background-color:#eee;">
						  	<!--<small class="pull-right" style="color:#888;padding-top:5px;">
						  		Revision: {{model.version}} Valid: 
						  		{% if model.validated %}Yes{%else%}No{%endif%}
						  	</small>-->
						  	<h3 style="margin:0;">
						  		<strong>{{model.name}}</strong> 
						  		{% if model.validated %}
						  			<i class="fa fa-leaf" style="color:#aaa;"></i>
						  		{% else %}
						  			
						  		{% endif %}
						  	</h3>
						  	
						  </div>

						  <div class="panel-heading" >
						  		{% if not model.validated %}
						  			<small>
						  				<strong style="color:#e50000;">This model is not validated yet!</strong><br/> It means there is probably something wrong with the model code. Once a model can be loaded properly and all its parameters, metadata, and reporting information can be read and parsed, it will be marked as validated. Only validated models can be run in the modeller.</small>
						  		{% endif %}

								<p style="">{{model.meta["abstract"]}}</p>

								{% if model.validated %}
									<a class="btn btn-default btn-sm" href="{{url_for('modeller.show_modeller',model_name=model.name)}}"><i class="fa fa-play" style="color:#888;"></i> Run model</a>
								{% else %}
									<!--<a class="btn btn-default btn-sm disabled" href="#"><i class="fa fa-warning" style="color:red;"></i></a>-->
								{% endif %}

								{% if current_user.is_admin %}
									<a class="btn btn-default btn-sm" href="{{url_for('admin.model_editor',model_name=model.name)}}"><i class="fa fa-pencil" style="color:#888;"></i> Edit model code</a>

									<a style="color:#888;" class="btn btn-default btn-sm pull-right" href="{{url_for('admin.model_toggle_pin',model_name=model.name)}}"><i class="fa fa-thumb-tack"></i></a>
								{% else %}
									<a class="btn btn-default btn-sm" href="{{url_for('admin.model_editor',model_name=model.name)}}"><i class="fa fa-search" style="color:#888;"></i> View model code</a>
								{% endif %}
						  </div>
						  {% if model.validated %}
						    <table class="table" style="font-size:12px;color:#555;">
						    	<tr><td style="padding-left:15px;">Time:</td><td>Runs {{model.time["timesteps"]}} timestep(s) starting at {{model.start}} UTC.</td></tr>
						    	<tr><td style="padding-left:15px;">Discretization:</td><td>{{model.discretization.name}} (max {{model.maxchunks}} chunks per job)</td></tr>
						    	<tr><td style="padding-left:15px;">Author:</td><td>{{model.meta["author"]}}</td></tr>
						    	<tr><td style="color:#aaa;padding-left:15px;" colspan="2">
								{% for tag in model.meta["tags"] %}
									<nobr><i class="fa fa-tag"></i> {{tag}}&nbsp;</nobr>
								{% endfor %}
						    	</td></tr>
						    </table>
						   {% endif %}
						</div>
		    		{%- endfor -%}
		    		</div>
				{% endfor %}
				</div> <!--/row-->


			<div class="row">
				<div class="col-md-12 col-sm-12">
					<hr>
					
				</div>
			</div>
		</div>

		{% endif %}
		<div class="col-md-4 col-sm-4">
			<div class="panel panel-default">
				{% if current_user.is_admin %}
					<div class="panel-heading" style="background-color:#f5f5f5;">
						<strong>GEMS Administration</strong>
					</div>
					<div class="list-group">
						<a href="/admin/datasets" class="list-group-item"><i class="fa fa-fw fa-database"></i> Datasets</a></a>
						<a href="/admin/discretization" class="list-group-item"><i class="fa fa-fw fa-pie-chart"></i> Domain Discretization</a>
						<a href="/admin/processing" class="list-group-item"><i class="fa fa-fw fa-gear"></i> Processing</a>
						<a href="/admin/workers" class="list-group-item"><i class="fa fa-fw fa-android"></i> Workers</a>
						<a href="/admin/models" class="list-group-item"><i class="fa fa-fw fa-leaf"></i> Models</a>
						<a href="/admin/users" class="list-group-item"><i class="fa fa-fw fa-user"></i> Users</a>
					</div>
				{% else %}
					<div class="panel-body">
						<p>
							<strong>Welcome, {{current_user.username}}!</strong>
						</p>
						<p>
						You are logged in as a regular user. This means you have 
						limited priveleges, and it is not possible to upload or 
						modify models. You can only run them with custom parameters.
						</p>
					</div>
				{% endif %}


			</div>
			<div class="panel panel-default">
				<div class="panel-heading" style="background-color:#f5f5f5;">
					<strong>API Access</strong>
				</div>
				<div class="panel-body">
					<p>
						Your API access token is:
					</p>
					<p style="text-align:center;">
						<code>{{current_user.api_token}}</code> <a href="{{url_for('site.myaccount_reset_api_token')}}" class="btn btn-xs btn-default"><i class="fa fa-refresh" style="color:#888;"></i>
</a>
					</p>
					<p style="margin-bottom:0">
						Please refer to your <a href="{{url_for('site.myaccount')}}">account details</a> page and the GEMS documentation for more information on API access. 
					</p>
				</div>
			</div>

			{% if current_user.is_admin %}
			<div class="panel panel-default">
				<div class="panel-heading" style="background-color:#f5f5f5;">
					<strong>Hidden models</strong>
				</div>

				<div class="panel-body" style="margin-bottom:0">
					<p>
					{% if not other_models %}
						No hidden models found. Click the pin on any model on the left to hide it.
					{% else %}
						These models are visible only to admin users. Click the pin icon to make them available for everybody. These models can be used for testing and development purposes without risking that other useds will load them in the modeller.
					{% endif %}
					</p>
				</div>


				<table class="table table-condensed">
					<tbody>
					{% for model in other_models %}
						{% if not model.disabled %}
						<tr>
							{% if model.validated %}
								<td style="vertical-align:middle;padding-left:15px;">{{model.name}}</td>
							{% else %}
								<td style="vertical-align:middle;padding-left:15px;color:#e50000;">{{model.name}}</td>
							{% endif %}
							
							
							<td style="vertical-align:middle;" class="text-right">
							{% if model.validated %}
								<a class="btn btn-default btn-sm" href="{{url_for('modeller.show_modeller',model_name=model.name)}}"><i class="fa fa-play" style="color:#888;"></i></a> 
							{% else %}
								<a class="btn btn-default btn-sm disabled" href="#"><i class="fa fa-play" style="color:#888;"></i></a>
							{% endif %}
								<a class="btn btn-default btn-sm" href="{{url_for('admin.model_editor',model_name=model.name)}}"><i class="fa fa-pencil" style="color:#888;"></i></a>
								<a style="color:#888;" class="btn btn-default btn-sm" href="{{url_for('admin.model_toggle_disable',model_name=model.name)}}"><i class="fa fa-trash"></i> Delete</a>
								<a style="color:#888;" class="btn btn-default btn-sm" href="{{url_for('admin.model_toggle_pin',model_name=model.name)}}"><i class="fa fa-thumb-tack"></i></a>
							</td>
						</tr>
						{% else %}
						<tr>
							<td style="vertical-align:middle;padding-left:15px;color:#888;">{{model.name}}</td>
							<td style="vertical-align:middle;color:#888;" class="text-right">
								<a style="color:#888;" class="btn btn-default btn-sm disabled" href="{{url_for('admin.model_toggle_disable',model_name=model.name)}}"><i class="fa fa-trash"></i> Deleted</a>
							</td>
						</tr>
						{% endif %}
					{% endfor %}




					</tbody>
					</table>


			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<strong>Create a new model</strong>
				</div>
				<form method="POST" action="{{url_for('admin.models')}}">
				<table class="table table-condensed">
					<tbody>
						<tr>
							<td style="vertical-align:bottom;padding-left:15px;padding-top:15px;padding-bottom:15px;width:100%;border:0">
								<p>Choose a cool model name like <code>my_crop_model</code>:</p>
								<input type="text" class="form-control input-sm"  style="width:100%" id="modelname" name="modelname" placeholder="Only alphanumeric characters, no spaces.">
							</td>
							<td style="vertical-align:bottom;color:#888;;padding-top:15px;padding-bottom:15px;border:0" class="text-right">
								<button type="submit" class="btn btn-default btn-sm"><i class="fa fa-plus"></i> Create</button>
							</td>
						</tr>
					</tbody>
				</table>
					
				</form>
			</div>
			{% endif %}
		</div>


	</div>



{% endblock %}

webapp/templates/site/models.html
{% extends "base.html" %}

{% block content %}

	<h2>List of models</h2>
	<p>
		Choose your poison:
	</p>
	<ul>
	{% for model in models %}
		<li><a href="{{url_for('modeller.show_modeller',model_name=model.name)}}">{{model.name}}</a>
	{% endfor %}
	</ul>
{% endblock %}

webapp/templates/site/myaccount.html
{% extends "base.html" %}

{% block content %}
	{% if not current_user.is_anonymous() %}
		<h2>Account details: {{current_user.username}}</h2>
		<p>
			Your API access token is: <code>{{current_user.api_token}}</code>
		</p>
		<p>
			You can test your access to the API with the following command: <code>curl --user {{current_user.username}}:{{current_user.api_token}} {{url_for('api.home',_external=True)}}</code> which should return a 200 OK with a JSON response containing <code>"authenticated": true</code>.
		</p>
	{% else %}
		<h2>You must be logged in to view this page.</h2>
	{% endif %}

	{% if current_user.is_admin %}
		
	{% endif %}

{% endblock %}